DROP PROCEDURE IF EXISTS TRIANGLE;
DELIMITER //
CREATE PROCEDURE TRIANGLE(n INT)
BEGIN
    SET @i = 0;
    REPEAT
        SELECT REPEAT('* ', @i := @i + 1);
    UNTIL @i >= 20 END REPEAT;
END
//
DELIMITER ;
CALL TRIANGLE(20);
